{% set version = "1.3.2" %}
{% set name = "cvxopt" %}
{% set suitesparse_for_win_version = "7.8.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 3461fa42c1b2240ba4da1d985ca73503914157fc4c77417327ed6d7d85acdbe6
  # on windows, building suitesparse in directly works much better than trying to build it separately and link it in
  {% if win %}
  - url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v{{ suitesparse_for_win_version }}.tar.gz
    sha256: fe3bc7c3bd1efdfa5cffffb5cebf021ff024c83b5daf0ab445429d3d741bd3ad
    folder: suitesparse
    patches:
      - 0001-remove-BLAS_NO_UNDERSCORE-on-windows.patch
  {% endif %}

build:
  number: 0
  # mkl is incompatible with GPL
  skip: true  # [blas_impl == 'mkl']
  ignore_run_exports:  # [win]
    - glpk  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=45
    - pip
    - dsdp 5.8
    - fftw {{ fftw }}
    - glpk {{ glpk }}
    - gsl {{ gsl }}
    - openblas-devel {{ openblas_devel }}  # [blas_impl == "openblas"]
    # suitesparse is linked against on windows, and compiled-in on windows, because yeah, windows.
    - suitesparse {{ suitesparse }}  # [not win]
    - setuptools-scm >=6.2
  run:
    - python
    - gsl
    - fftw
    - dsdp
    - glpk
    - suitesparse  # [unix]

test:
  source_files:
    # examples are required to run tests
    - tests/*
    - examples/*
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - pytest -vv tests

about:
  home: https://cvxopt.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL
  summary: Convex optimization package
  description: |
    Python Software for Convex Optimization
  doc_url: https://cvxopt.org/userguide
  dev_url: https://github.com/cvxopt/cvxopt

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
