{% set version = "1.3.0" %}

package:
  name: cvxopt
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
    sha256: 00b1b232f9d1f902d578a9d75814b67fa020758d5ae422e28ca8cef6269fa5c6
    patches:
      - fix_frame.diff

  # on windows, building suitesparse in directly works much better than trying to build it separately and link it in
  - url: http://faculty.cse.tamu.edu/davis/SuiteSparse/SuiteSparse-5.2.0.tar.gz           # [win]
    sha256: 00b1b232f9d1f902d578a9d75814b67fa020758d5ae422e28ca8cef6269fa5c6              # [win]
    folder: suitesparse                                                                   # [win]

build:
  number: 0
  skip: True  # [blas_impl == 'openblas' and win]
  skip: true  # [win and py<35]

requirements:
  build:
    - {{ compiler("c") }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - dsdp
    - fftw                           # [blas_impl != "mkl"]
    - glpk
    - gsl
    - mkl-devel  {{ mkl }}           # [blas_impl == "mkl"]
    - openblas-devel {{ openblas }}  # [blas_impl == "openblas"]
    - python
    - setuptools
    # suitesparse is linked against on windows, and compiled-in on windows, because yeah, windows.
    - suitesparse                    # [unix]

  run:
    - python
    - gsl
    - fftw
    - dsdp
    - glpk
    - suitesparse   # [not win]

test:
  imports:
    - cvxopt
    - cvxopt.base
    - cvxopt.blas
    - cvxopt.cholmod
    - cvxopt.lapack
    - cvxopt.misc_solvers
    - cvxopt.umfpack
    - cvxopt.glpk
    - cvxopt.fftw
  source_files:
    - tests/*
    - examples/*

about:
  home: http://cvxopt.org
  license: GPL 3
  license_file: LICENSE
  summary: Convex optimization package

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
