{% set version = "1.3.0" %}
{% set suitesparse_for_win_version = "5.7.2" %}

package:
  name: cvxopt
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
    sha256: 00b1b232f9d1f902d578a9d75814b67fa020758d5ae422e28ca8cef6269fa5c6

  # on windows, building suitesparse in directly works much better than trying to build it separately and link it in
  - url: https://github.com/DrTimothyAldenDavis/SuiteSparse/archive/v{{ suitesparse_for_win_version }}.tar.gz  # [win]
    sha256: fe3bc7c3bd1efdfa5cffffb5cebf021ff024c83b5daf0ab445429d3d741bd3ad  # [win]
    folder: suitesparse  # [win]
    patches:   # [win]
      - 0001-remove-BLAS_NO_UNDERSCORE-on-windows.patch                                                        # [win]

build:
  number: 0
  # mkl is incompatible with GPL
  skip: True  # [blas_impl == 'mkl']
  # no suitesparse support on s390x
  skip: true  # [s390x]
  ignore_run_exports:  # [win]
    - glpk             # [win]
requirements:
  build:
    - {{ compiler("c") }}
    - m2-patch  # [win]
  host:
    - python
    - setuptools
    - pip
    - wheel  
    - dsdp 5.8
    - fftw 3.3.9
    - glpk 4.65
    - gsl 2.7.1
    - openblas-devel {{ openblas }}  # [blas_impl == "openblas"]
    # suitesparse is linked against on windows, and compiled-in on windows, because yeah, windows.
    - suitesparse 5.10.1            # [not win]
  run:
    - python
    - gsl
    - fftw
    - dsdp
    - glpk
    - suitesparse                    # [unix]

test:
  source_files:
    - tests/*
    - examples/*
  requires:
    - pytest
    - pip
  commands:
    - pip check

about:
  home: https://cvxopt.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  license_family: GPL
  summary: Convex optimization package
  description: |
    Python Software for Convex Optimization
  doc_url: https://cvxopt.org/userguide
  dev_url: https://github.com/cvxopt/cvxopt

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
