{% set version = "1.1.8" %}

{% set variant = "openblas" %}


package:
  name: cvxopt
  version: {{ version }}

source:
  fn: cvxopt-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/cvxopt/cvxopt-{{ version }}.tar.gz
  md5: d4ff0a0e51aba93f838a70302a088eea
  patches:
    # Fix the environment variable used for SuiteSparse includes.
    # See this PR ( https://github.com/cvxopt/cvxopt/pull/60 ).
    - cvxopt_PR_60.diff

build:
  skip: true  # [win]
  number: 201
  features:
    - blas_{{ variant }}

requirements:
  build:
    - python
    - setuptools
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - gsl
    - fftw
    - glpk
    - suitesparse 4.4.*

  run:
    - python
    - blas 1.1 {{ variant }}
    - openblas 0.2.18*
    - gsl
    - fftw
    - glpk

test:
  imports:
    - cvxopt

about:
  home: http://cvxopt.org
  license: GPL 3
  summary: Convex optimization package

extra:
  recipe-maintainers:
    - jakirkham
    - jjhelmus
    - martinandersen
