travis:
  secure:
    BINSTAR_TOKEN: SfzEw1FZOTut5FFVLzHCemxFPlcj9mGvHOqbOirr1HB79+yH5VRT/dLOm4ez2CiyZrNhWjWrij33VUE/n7OV2uDlGe9dgrDDZ3pxzie2eMkUJgfMxfaSed33BAaT+/75pm3Ylliv2N3zDgA5AWtPsXjwxkTmhvGWBhYVNJveiMtoL1/pmmZmAHQRUwe0LTeUs+a348FiwjCHsDf4DdIGkThEYesaVd7+bp5igBVt7CY6TwHuFQ5RHTB41nS8DnWPtFndqeUb/IhX+bb8UiCOGn1pBlPzpZOgp6wg4NtiU8ElfZBpCcLekQRdiIq0Ktr/PaNR3rwT5SqAcaesNyG1Q8tbdLk79CdJRHhnSj/CRz7oasCZ65z8SgYGkO/DMt4RxH7J04e2A6S3AVsQep4ctfxI0cyNrE/YjkooWtYSRIPu8y4MeBcUjvNThJnurSDnLOf9locckSxxCnjsR94TYh8bfrVCVC8ougBGdhihp+btIXiCK0tRsmCfRaWBP7LObAtG8oo7SCh2OJm3OJAD/HaTIdU26gqtgRBRyOVZyu8CgeJjh45z9thCBnmWWEycbygX7Ln27W9vExasGmHvXI7FAmUMVN+Dks0XgXPJc9NRXfXpA+jXDjdWhvaXU+yGgsVcf9Zk+jeI3DxlT3nsmzCN/y/fTus7lQF2yEBhkiw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
