travis:
  secure:
    BINSTAR_TOKEN: j6lLqjBhLhRzTAnR+L3jssha0lPcedbrBzzvaspA65haJ19A53mohevoEVLivacQpusfKEQrNQTd4pXi9qoNpg30YN7A9ngLyrpunw/qzJ46DaeA7T6KDoT5i3pZ4wa26uz9ElvPy3kp+libmWfVfRXftRWE0LLhbqK++rFUIvSjqyMbLQu+Gej6uRuFhLSREoOAdFAz4amkaKgxf1fCKs6LtlOCIY4zSgVQGHCIGIzBc5yzirMNVYd64AgltVhsm/q8Bfe3vlqeuLzijtGhC23k/xxvy5bBWHZjPbn4FAsRUC+i7IjRChN4RkeEgSYfji6GdxW1hjZfQHDju4Z9MRpF2Vi+hMyzLgkxmCQhoHoWDKgrYC86X2BdTKm51dx+bljUFuNpfevn+dgZbIcIullVSMIfDHa3T1qbpY7D0tSIqg16eZcofVjdZSb7zzDWy+Nm4kkDrReoioajAeqcqVRY0kQ+iKS5LjdKhsMcxWPkYaPKiKlzk+1EkGeZmDBBhTgyN87fnp6oHTt9abLIFGa9bWYom2z/ISEBLdU46IvFz6ZKkLYZiqGf7s0gu+oya7e9Q7B7Oe+3fLAOIV9aOMh2GnaVHIOtg08xxZZS+WCTjS61gy/1iA6XubV4LuOzI3D475MfK3Eg8mCk6ed1CAYjxCuXE3mBb9anjm/Kcow=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
